run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosimple
    - gocyclo
    - gofumpt
    - revive
    - misspell
    - sqlclosecheck
    - bodyclose

  disable:
    - gocritic
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo

    - text: "should have comment"
      linters:
        - revive

  max-same-issues: 10
  max-issues-per-linter: 50

linters-settings:
  gocyclo:
    min-complexity: 15

  revive:
    severity: warning
    rules:
      - name: indent-error-flow
      - name: errorf
